In [2]:
import pandas as pd
import numpy as np

## Creating arrays

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.full(10, 3.14)
# Size and element

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [12]:
python_list = [1, 2, 3, 4, 5]
a = np.array(python_list)
a

array([1, 2, 3, 4, 5])

In [13]:
a[2]

np.int64(3)

In [15]:
a[2] = 10 # Assigned third element to 10
print(a)

[ 1  2 10  4  5]


In [20]:
np.arange(10, 100)
# Similar to range function in python.

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [23]:
np.arange(10, 100, 11)
# Similar to range, starts from 10 goes until 100, in the step of 11

array([10, 21, 32, 43, 54, 65, 76, 87, 98])

In [25]:
np.linspace(0, 1, 11)
# Creates an array of size 11 from element 0 to 1 including both

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [26]:
np.linspace(0, 1, 12)


array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

## Multi-dimensional arrays

In [28]:
np.zeros([5, 2])
# We provide shape i.e. 5 rows and 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
d2_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [33]:
d2_array[0, 1]

np.int64(2)

In [34]:
d2_array[0, 0] = 100

In [35]:
d2_array

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [37]:
d2_array[1]
# Return row 1

array([4, 5, 6])

In [38]:
d2_array[2]

array([7, 8, 9])

In [39]:
d2_array[2] = [200, 300, 400]

In [40]:
d2_array

array([[100,   2,   3],
       [  4,   5,   6],
       [200, 300, 400]])

In [43]:
d2_array[:, 1]
#Returns 2nd column

array([  2,   5, 300])

In [46]:
d2_array[:, 2] = np.ones(3)
# As long as it is in the shape of array

In [47]:
d2_array

array([[100,   2,   1],
       [  4,   5,   1],
       [200, 300,   1]])

## Randomly generated arrays

In [53]:
np.random.rand(5, 2)
# Random numbers between 0 and 1 of size 5, 2
# Take numbers from uniform distribution

array([[0.62113383, 0.52914209],
       [0.13457995, 0.51357812],
       [0.18443987, 0.78533515],
       [0.85397529, 0.49423684],
       [0.84656149, 0.07964548]])

In [52]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [55]:
np.random.randn(5, 2)
# std normal distribution

array([[-1.42121723, -0.1534952 ],
       [-0.26905696,  2.23136679],
       [-2.43476758,  0.1127265 ],
       [ 0.37044454,  1.35963386],
       [ 0.50185721, -0.8442137 ]])

In [101]:
np.random.randint(10, 12)

10

In [102]:
np.random.rand(5, 2)*100

array([[29.30232318, 52.40668753],
       [35.66242811,  4.56789652],
       [98.31534454, 44.13549194],
       [50.40004394, 32.35413175],
       [25.97447527, 38.68898853]])

In [105]:
np.random.randint(low=0, high=100, size=(5, 2))
# low is included and high is not 

array([[79, 91],
       [96, 49],
       [40, 46],
       [59, 73],
       [78, 94]])

## Element wise operations

In [107]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [111]:
a + 1
# every element is added to 1

array([1, 2, 3, 4, 5])

In [112]:
a * 2
# every element gets multiplied by 2

array([0, 2, 4, 6, 8])

In [115]:
b = ((a/100)  + 2)**2
b

array([4.    , 4.0401, 4.0804, 4.1209, 4.1616])

In [117]:
a + b
# Element wise sum will happen

array([4.    , 5.0401, 6.0804, 7.1209, 8.1616])

In [119]:
a  * b
# Element wise multiplication

array([ 0.    ,  4.0401,  8.1608, 12.3627, 16.6464])

In [122]:
a ** b
# element wise exponent

array([  0.        ,   1.        ,  16.91697838,  92.50580325,
       320.28224198])

## Comparison Operators

In [123]:
a


array([0, 1, 2, 3, 4])

In [128]:
a >= 5
# Comparison is also performed element wise

array([False, False, False, False, False])

In [125]:
b

array([4.    , 4.0401, 4.0804, 4.1209, 4.1616])

In [126]:
a > b

array([False, False, False, False, False])

In [127]:
a >= b

array([False, False, False, False, False])

In [130]:
a[a>b]

array([], dtype=int64)

## Summarizing Operations

In [132]:
a

array([0, 1, 2, 3, 4])

In [133]:
a.min()

np.int64(0)

In [134]:
a.sum()

np.int64(10)

In [135]:
a.max()

np.int64(4)

In [136]:
a.std()

np.float64(1.4142135623730951)

In [137]:
a.var()

np.float64(2.0)

In [138]:
d2_array

array([[100,   2,   1],
       [  4,   5,   1],
       [200, 300,   1]])

In [139]:
d2_array.sum()

np.int64(614)

In [140]:
d2_array.sum(axis = 0)

array([304, 307,   3])